### ISSUE TITLE
Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by ricardoruwer** [iroddis/asdf-mysql#1]
Hello :) that's a nice plugin!

I just installed it following these steps:
1. `brew install gcc xz`
2. `asdf plugin-add mysql`
3. `asdf install mysql 5.7.27`

And when I try to access the MySQL using the command: 
```mysql -u root```

I got the following error:
```ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)```

Apparently we have to start the MySQL? But how?

Like this other asdf plugin to `postgres` (https://github.com/smashedtoatoms/asdf-postgres) we have this command to start the services: `pg_ctl start`

Maybe we need something like this here? 🤔

**Comment by iroddis** [comment]
Hey @ricardoruwer thanks for the feedback. I've added steps for mysql-8.x , and I'll work on adding in support for 5 as well. If you run into any other problems, please let me know.
