### ISSUE TITLE
Install command response empty

### ISSUE THREAD

**Issue by nomasprime** [iroddis/asdf-mysql#19]
`asdf install mysql 5.7.36`

```
-----------------------------------------------------------------------------
Welcome to the University of Kent's UK Mirror Service.

More information can be found at our web site: https://www.mirrorservice.org/
Please send comments or questions to help@mirrorservice.org.
-----------------------------------------------------------------------------

receiving file list ... done

sent 39 bytes  received 17 bytes  112.00 bytes/sec
total size is 0  speedup is 0.00
```

**Comment by nomasprime** [comment]
Relates to [this](https://github.com/iroddis/asdf-mysql/issues/8).

Seems like you can install any version you want, so long as it's version 8.

**Comment by iroddis** [comment]
> Seems like you can install any version you want, so long as it's version 8.

That's the kind of variety I can get behind!

It looks like something's changed in how they're distributing binaries. Anything pre-6.x is missing the pre-built OSX binaries. I'm working on a build-from-source solution now.

**Comment by iroddis** [comment]
Ok, that latest commit should set you up for 5.X. Let me know if you're still having problems.
