### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by tasugo** [iroddis/asdf-mysql#2]
I'm using Manjaro 20.0.1 and installation fails:

```bash
➜ asdf install mysql 8.0.19

~/.asdf/plugins/mysql/bin/install: line 17: arch: command not found
```

**Comment by grafixen** [comment]
The URL (mysql.he.net/mysql/Downloads) where the plugin seems to check for MySql versions seem to be dead

**Comment by ctrlaltdylan** [comment]
You'd think it'd be easy to find a google cache'd page or at least an index of MySQL versions, but alas nothing yet.

**Comment by ctrlaltdylan** [comment]
Maybe the github repo tags list is the most definitive index?

https://github.com/mysql/mysql-server/tags

**Comment by grafixen** [comment]
If you look into the code you'll see that the files were stored in the server 

`rsync://mysql.he.net/mysql/Downloads/MySQL-"${MAJOR}.${MINOR}"/${FILE} \
    ${tmp_download_dir}/. 2>/dev/null`

Version detection and tagging is also done through the same server.

**Comment by ctrlaltdylan** [comment]
Right exactly. I'm just thinking since those pages have since 404'd it might be best to just rely on the MySQL github rep for version parsing & retrieval.

**Comment by iroddis** [comment]
I updated the server used to find versions and retrieve versions to something that works. Sorry, I wasn't receiving emails about these issues. Hopefully this new site will be a little more robust. If you're still running into issues, just let me know.

**Comment by ctrlaltdylan** [comment]
hi @iroddis that's awesome. I've ended up using brew to install 1 mysql version on my machine which hasn't been an issue yet. But would be happy to try out this once I need to upgrade to mysql 5.8.
