### ISSUE TITLE
Archlinux support in ASDF MySQL

### ISSUE THREAD

**Issue by Ruluk** [iroddis/asdf-mysql#23]
Hey!

I tried installing MySQL through ASDF in Archlinux. So far it seems to be working alright, but I had to install some packages:

```
Rsync (to list and install from ASDF)
Libaio (to get libaio as mentioned in the readme)
Ncurses5-compat-libs (to get libtinfo as mentioned in the readme)
Numactl (to get libnuma. This one is not mentioned in the readme but it was required for installation)
```

I thought letting you know of these requirements could be useful in the Readme.

**Comment by iroddis** [comment]
Thanks for the feedback. I've added rsync to the readme, since that one makes sense on all platforms.

For your other packages, are they specific to Arch? Which version of MySQL were you installing?

**Comment by Ruluk** [comment]
`ncurses5-compat-libs` is the best way in Arch to get libtinfo (at least through a package).
`libnuma` was required for MySQL 8. If I were to guess, it is required for all but maybe comes preinstalled in Debian/Ubuntu.

**Comment by iroddis** [comment]
Thanks very much! I've updated the README with that info.
