### ISSUE TITLE
asdf list all mysql - no results

### ISSUE THREAD

**Issue by redesigned** [iroddis/asdf-mysql#24]
`asdf list all mysql`
no results returned after a long timeout (2m13s)

**Comment by iroddis** [comment]
I just tried it out, and it's working for me. Are you still having the problem? Can you ping www.mirrorservice.org ?

**Comment by httpete** [comment]
on Centos 8 it just hangs:

rsync --progress --verbose -arv rsync://rsync.mirrorservice.org/ftp.mysql.com/Downloads/MySQL-8.0/mysql-8.0.28.zip
opening tcp connection to rsync.mirrorservice.org port 873
