### ISSUE TITLE
Only works with rsync

### ISSUE THREAD

**Issue by httpete** [iroddis/asdf-mysql#25]
Hi, I have an environment which forbids rsync .
Can we have a flag to use wget instead?

**Comment by iroddis** [comment]
Just pushed a change to move use cURL instead of rsync. Can you try it out and let me know how that works for you?

**Comment by httpete** [comment]
as if by magic, it worked first shot this is huge. Thank you. I think curl is more ubiquitous. 

```
[psuser@machine~]$ asdf list-all mysql
4.1.21
4.1.22
5.0.95
5.0.96
5.1.72
5.1.73
5.2.3
5.4.3
5.5.60
5.5.61
5.5.62
5.6.49
5.6.50
5.6.51
5.7.36
5.7.37
5.7.38
6.0.11
8.0.27
8.0.28
8.0.29

**Comment by httpete** [comment]
the only strangeness I am seeing now is that I Can do the install, set to global, I can see the installed mysql in the installs directory. But I keep getting command not found. I don't know if this was related to your change ( I doubt) or it's some other issue.

**Comment by httpete** [comment]
I can verify, that the shims/mysql is missing.  It worked perfectly with asdf 0.9.0, but I tried backing off to 0.9.0 and it still doesn't make the shims for mysql.

**Comment by iroddis** [comment]
That's strange, I just tried a fresh install, and that didn't happen to me. Could you see if `asdf reshim mysql` solves the problem?

**Comment by httpete** [comment]
tried 10 times. Every other shim is in there perfectly. The mysql one just wont appear. This is on Centos 8 Stream if that matters?

**Comment by iroddis** [comment]
I'll need to get a VM set up to test out that theory. Are there any binaries in `~/.asdf/installs/mysql/X.X.X/bin` for the version that's set global?

**Comment by httpete** [comment]
yep bin directory full of tasty mysql binaries.

**Comment by httpete** [comment]
what part of your code creates the shims?

**Comment by iroddis** [comment]
asdf core does the shimming, but the latest version of asdf-mysql put the binaries `~/.asdf/installs/mysql/{version}/mysql-directory/...` , so the shimming code couldn't find anything to wrap.

Latest version fixes that issue. Could you please erase anything in `~/.asdf/installs/mysql/*`, and try the installation again?

**Comment by httpete** [comment]
FIRST SHOT like butter. Awesome @iroddis !

**Comment by iroddis** [comment]
Great! Thanks for confirming and bearing with me. I'll close this out for now, but feel free to reopen it if needed.

**Comment by iroddis** [comment]
None of the plugin code creates the shims, it’s taken care of in the main asdf code.
