### ISSUE TITLE
Issues installing mysql 5.6.51 on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by mateomurphy** [iroddis/asdf-mysql#27]
I ran into a few issues on a recent install:

* `libncurses5` was required,  necessitating a `sudo apt-get install libncurses5`
* `mysql_install_db` wasn't in PATH, and needed to be run as `scripts/mysql_install_db` from `~/.asdf/installs/mysql/5.6.51` 

The first is perhaps just a documentation issue, but perhaps there's a solution for the second?

**Comment by iroddis** [comment]
Hey @mateomurphy , thanks for the report. I've updated the documentation, and added the `scripts/` directory so that it's scripts get shimmed correctly.
