### ISSUE TITLE
8.0.30

### ISSUE THREAD

**Issue by httpete** [iroddis/asdf-mysql#28]
Hi,

I have an email in to the mirrorservice because for some reason 8.0.30 isn't there. This is just a heads up if anyone else is hitting this and I will update this ticket.

**Comment by httpete** [comment]
I just heard back from them and they say:

It looks like the MySQL rsync service has stopped working at some point. Looking around at other mirrors I see they're in the same state. I'll see if I can get them to sort it, but it may well be that Oracle have just decided they don't want people distributing it any more.

Tim.

If this is the case, asdf-mysql needs a new way to get versions.

**Comment by iroddis** [comment]
It looks like 8.0.30 still isn't available on mirrorservice, and the only way I can find to download it is via the web UI. Short of hard-coding URLs into the plugin, it seems like this distribution is a bit broken.

Oracle's passive aggressive stance towards open source knows no bounds... I'll keep checking for a workaround, but would people be interested in an `asdf-mariadb` option?

**Comment by httpete** [comment]
Don't they allow install via yum or other package managers? Why would they care if they distribute this way? Are we sure that they are blocking it?

**Comment by iroddis** [comment]
Many users want/need to match MySQL versions running in prod / dev / work environments. Package managers don't generally allow you to specify the version to install, or if they do, they don't allow multiple installs with different versions. `asdf` and similar programs allow you to do both of those things, which makes it easier to do development work, test the impact of version changes, etc.

I'm not sure they're blocking, but so far I haven't found a reliable way to pull the binaries that doesn't involve full-on scraping of their website forms. I have zero faith that the forms will remain consistent enough to be useful over the long term.

I've reached out to mirrorservice as well to see if I can help with their efforts, or figure out an alternate source.

**Comment by httpete** [comment]
I agree. That is why I love asdf. It makes it so easy to manage a dev env. I can't understand why Oracle would stop distribution.

**Comment by iroddis** [comment]
Could you give the latest master a try, please? I've switched sources away from MirrorService to the amazing, hand-maintained database of the [dbdeployer](https://github.com/datacharmer/dbdeployer) project.

The advantages are many:

- Faster overall querying for available versions
- Easier to identify exactly which pre-built binaries are available for which platforms
- HTTPS all the way through using CDNs, so hopefully more robust.

**Comment by httpete** [comment]
worked as if by magic! absolutely fantastic! I Can't thank you enough @iroddis

**Comment by httpete** [comment]
For others I:

```mysqladmin -u root -p shutdown
asdf plugin update --all
asdf install mysql 8.0.30
asdf global mysql 8.0.30

mysqld_safe &

**Comment by iroddis** [comment]
I'm glad to hear it! After finding dbdeployer, it was just a case of extracting the information from their JSON database. I'll close this for now, but please let me know if you run into any other issues.

Also, thank you very much for reporting this, @httpete, and following up with MirrorService in the first place. That leg work was really helpful!
