### ISSUE TITLE
Unable to list versions since `mysql.he.net` does not exist anymore

### ISSUE THREAD

**Issue by mrmstn** [iroddis/asdf-mysql#3]
Hi there

Looks like the subdomain `mysql.he.net` does not  exist anymore. This makes it impossible to list versions
```
> dig mysql.he.net

; <<>> DiG 9.11.21-RedHat-9.11.21-1.fc32 <<>> mysql.he.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55941
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mysql.he.net.			IN	A

;; AUTHORITY SECTION:
he.net.			1266	IN	SOA	ns1.he.net. hostmaster.he.net. 202007230 10800 1800 604800 86400

;; Query time: 10 msec
;; SERVER: 157.161.9.7#53(157.161.9.7)
;; WHEN: Fri Jul 24 10:46:42 CEST 2020
;; MSG SIZE  rcvd: 92
```

**Comment by dtbaker** [comment]
Is there a recommended alternative mysql asdf plugin?

**Comment by iroddis** [comment]
I just pushed a fix for the missing server. Give it a try and let me know if it's working for you.

**Comment by jbarreneche** [comment]
Thanks! 

Just letting you know that installation works (if the version exists) but listing all available versions doesn't work (at least for macos X), which makes hard to know which versions you can install (specially on mac since not all of the versions are available.

**Comment by h35514n** [comment]
@jbarreneche

>  listing all available versions doesn't work

The last line in the `list-all` script should be 

```sh
echo "$versions" | tr '\n' ' '
```

instead of

```sh
echo "$versions" | tr ' ' '\n'
```

PR here: https://github.com/iroddis/asdf-mysql/pull/4
