### ISSUE TITLE
Could not find OpenSSL on the system when access openSSL

### ISSUE THREAD

**Issue by jxpeng98** [iroddis/asdf-mysql#30]
Hello, 

When I install mysql via asdf, I faced the issue in the final step to setup the openssl.

```
mysql_ssl_rsa_setup --datadir=$DATADIR
2022-12-26 14:35:42 [ERROR]   Could not find OpenSSL on the system
```

When I check openssl, it shows:
```
which openssl
/Users/pengjiaxin/.asdf/shims/openssl
```

May I know how could I solve this problem?

**Comment by iroddis** [comment]
Hi @jxpeng98 . I can't find any asdf packages that would install `openssl`. Can you give me the output of `asdf shim-versions openssl` ?

The MySQL installer needs to know where OpenSSL is installed. If it's not in a standard location, that means updating `CXXFLAGS` with the include path and `LD_LIBRARY_PATH` with the path to the library. You may need to update those environment variables in your shell to get this to work.

**Comment by jxpeng98** [comment]
Hi @iroddis ,

Here is the output:
```
asdf shim-versions openssl
python miniforge3
```

I uninstall the python and reinstall MySQL via asdf. 

Problem solved! There are no conflicts with the homebrew version.

Thanks!
