### ISSUE TITLE
Basic database setup missing error messages

### ISSUE THREAD

**Issue by viraptor** [iroddis/asdf-mysql#31]
The install / running instructions could use a mention of `--lc-messages-dir`. Without the option, all errors are returned as codes only, without the error message.

In practice you need to run:
```
mysqld --lc-messages-dir=$HOME/.asdf/installs/mysql/{the_version}/share --other-options
```

(at least for the 5.7 versions - haven't tried v8)

**Comment by iroddis** [comment]
Thanks very much for the hint, I've updated the README with that info, adding in some shell to automatically determine the version.
