### ISSUE TITLE
Can't find mysql 8.0.33

### ISSUE THREAD

**Issue by httpete** [iroddis/asdf-mysql#32]
This has been perfect since the move to dbdeployer under the hood, but now when I do list-all it doesn't find 8.0.33.

**Comment by iroddis** [comment]
I think you've identified the issue already; dbdeployer doesn't have that version listed in its database, yet. I've created an [issue with them](https://github.com/datacharmer/dbdeployer/issues/164).

**Comment by httpete** [comment]
@iroddis I have tried looking into the documentation and trying to figure out how to add the 8.0.33 to the upstream project. It's not exactly push button 😆 . I have contacted the owner of that repo, he hasn't replied.

**Comment by httpete** [comment]
I have tried by adding this PR:
https://github.com/datacharmer/dbdeployer/pull/167

**Comment by httpete** [comment]
OK I updated it with that PR @iroddis but what is really odd is I can't see it when I do asdf list-all mysql? I tried updating and verifying - it is in fact there in the tarball  list?

**Comment by iroddis** [comment]
Hi @httpete thanks very much for submitting that PR to their project. I get `8.0.33` as an option now when I do `asdf list-all mysql`. Maybe you're hitting a cache? This plugin doesn't do any kind of caching, each time you run it the script will use `curl` to get the latest JSON file from [dbdeployer/master](https://raw.githubusercontent.com/datacharmer/dbdeployer/master/downloads/tarball_list.json).

**Comment by httpete** [comment]
What os are you on? I am on Linux 64. I tried to follow his directions but I think he made a mistake.

**Comment by httpete** [comment]
Why do we want the minimal one? Is that required? I see that the script you have here filters for minimal=false, but somehow I didn't add that flavor to their repo. Im working on it, hopefully he can help.

**Comment by iroddis** [comment]
I removed the requirement for the minimal installation, it should work if you update. I'll add support to add minimal / full tags.

**Comment by iroddis** [comment]
I've added a branch called `tagged_distro`, which will differentiate between `-full` and `-minimal` distributions. I'm hesitant to change the names in case anyone relies on the semver names, so I'll hold off on merging that branch for now.

**Comment by httpete** [comment]
So I am talking to @datacharmer to see if he can fix the fact that I missed the fact that we shouldn't have updated it without --minimal. I am hoping he can, but soon it will be paved over by 8.0.34 and I will update with the right command next time. We seem to be working ok with the minimal version, I really don't know why someone would want the "maximal" version? I mean most people using asdf are using this for development I must imagine.

**Comment by httpete** [comment]
@iroddis - @datacharmer fixed the upstream issue with 8.0.33. Can you revert master to the way it was - which filtered for minimal = false? I Think we can safely go back to the way it was. The maximal package is there. Right now off master I can't install mysql and I get doubles in the list-all:

```
8.0.30
8.0.31
8.0.31
8.0.32
8.0.32
8.0.33
8.0.33

**Comment by iroddis** [comment]
Fixed, and I don't see the dupes anymore (except on Darwin/MacOS, where it's not unexpected).

**Comment by httpete** [comment]
all fixed. Everything working here as expected!
