### ISSUE TITLE
dbdeployer project seems unmaintained

### ISSUE THREAD

**Issue by httpete** [iroddis/asdf-mysql#34]
Hi,
https://github.com/datacharmer/dbdeployer/pull/173

I have worked to help, but he isn't replying. asdf-mysql should search for a better way to get mysql without this dependency. I am sure it is a non trivial thing.

**Comment by iroddis** [comment]
It is a bit non-trivial. Oracle has made it tough to just query these things ... they want you to go through their terrible web interface for maximal opportunity to upsell and capture information.

As a work around, I could add support for patch files for dbdeployer, taking your submitted PR and incorporating it into the pulled json. Alternatively we can just pull the upstream database and maintain a version ourselves.

To be honest, I barely use this module any longer, and I noticed that you offered to maintain dbdeployer. Do you have any interest in maintaining this asdf module?

**Comment by iroddis** [comment]
oh, looks like your PR was merged. We can still have the discussion around ongoing updates, though.

**Comment by httpete** [comment]
I’ll keep working dbdeployer as it works fine for the moment.On Oct 25, 2023, at 9:20 AM, Ian Roddis ***@***.***> wrote:﻿
oh, looks like your PR was merged. We can still have the discussion around ongoing updates, though.

**Comment by httpete** [comment]
@iroddis The dbdeployer has been officially abandoned. 8.0.33 will be the last that works with this plugin.
 I am in the same boat as you, I like asdf/mysql but I can get around this other ways. I think we should advertise this on the project to see if a maintainer is wanted or it's time to turn the lights off.

**Comment by iroddis** [comment]
Agreed, it's a sad day, but there's only so much effort anyone has to spend on dealing with Oracle's frankly OSS-hostile ways. I'll push a commit with a warning and a request for maintainer on the README and on install.
