### ISSUE TITLE
Start as a service?

### ISSUE THREAD

**Issue by ctsstc** [iroddis/asdf-mysql#6]
I was wondering if I could it start the global as a service, or is it supposed to just by manually started every time with the idea that every project could be running a different version. Then of course you could only work on one project at a time with that model.

Could it auto start when I open a project? But then we're back to, what happens when I open multiple directories 🤔 

I'm also now reconsidering if I should even have mysql in a version manager, since normally it's a singleton point of existence that you tend to just always have running and expect to just be a major revision most of the time. I know some people do need to jump between major versions though.

**Comment by iroddis** [comment]
There's definitely a case for a single version of MySQL. The use case for me was an easy way to install across multiple platforms, and better control over the database version. If you rely on your OS / homebrew, it could change versions underneath you. `asdf` provides more control for reproducible environments.

As for starting as a service, I think that would be fairly OS dependent. I'm happy to accept any PRs that make it easy :)
